"""New tables

Revision ID: 45bdc3e025d9
Revises: 767e83336ae7
Create Date: 2025-05-23 04:24:08.506104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bdc3e025d9'
down_revision: Union[str, None] = '767e83336ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('cnl_text', sa.Text(), nullable=False),
    sa.Column('clarity', sa.Integer(), nullable=True),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.Column('consistency', sa.Integer(), nullable=True),
    sa.Column('syntax_validity', sa.Integer(), nullable=True),
    sa.Column('modelability', sa.Integer(), nullable=True),
    sa.Column('ambiguity', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('uml_code', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['requirement_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_messages')
    op.drop_table('requirement_sessions')
    # ### end Alembic commands ###
